services:
  db:
    image: mysql:8
    container_name: gestorpro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestorpro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: gestorpro_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev

  prisma-studio:
    build: ./backend
    container_name: gestorpro_prisma_studio
    restart: always
    depends_on:
      - db
      - backend
    env_file:
      - ./backend/.env
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: npx prisma studio --hostname 0.0.0.0 --port 5555

  frontend:
    build:
      context: ./frontend
    container_name: gestorpro_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/.env:/app/.env
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"

volumes:
  mysql_data_volume:
