version: "3.8"

services:
  db:
    image: mysql:8
    container_name: gestorpro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestorpro
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql

  backend:
    build: ./backend
    container_name: gestorpro_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
    container_name: gestorpro_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host

volumes:
  mysql_data_volume:
